apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-configs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/morey-tech/back-stack
    path: crossplane/manifests/provider-configs
    targetRevision: HEAD
  destination: 
    name: in-cluster
    namespace: crossplane-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated: {}
