apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd

namespace: argocd

resources:
- ./namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/ha/install.yaml
- ./ingress.yaml

patches:
  - path: ./service.yaml
  - path: ./argocd-cm.yaml
