apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: crossplane-contrib-provider-helm-config
spec:
  serviceAccountTemplate:
    metadata:
      name: crossplane-contrib-provider-helm
