apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane

namespace: crossplane-system

# resources:
# - back-stack-configuration.yaml

helmCharts:
- name: crossplane
  includeCRDs: true
  namespace: crossplane-system
  releaseName: crossplane
  version: v1.14.4
  repo: https://charts.crossplane.io/stable
  valuesInline:
    args:
      - --enable-external-secret-stores

- name: ess-plugin-vault
  includeCRDs: true
  namespace: crossplane-system
  releaseName: crossplane
  version: 0.2.0
  # OCI requires helm => 3.8.0 and kustomize => v5.2.1
  repo: oci://xpkg.upbound.io/crossplane-contrib
  valuesInline:
    podAnnotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-token: "true"
      vault.hashicorp.com/role: "crossplane"
      vault.hashicorp.com/agent-run-as-user: "65532"
