apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-provider-configs

namespace: crossplane-system

resources:
- aws-providerconfig.yaml
- azure-providerconfig.yaml
- back-stack-configuration.yaml
- helm-controlerconfig.yaml
- helm-crb.yaml
- helm-providerconfig.yaml
- kubernetes-controlerconfig.yaml
- kubernetes-crb.yaml
- kubernetes-providerconfig.yaml
